name: Node.js CI

on:
  push:
    tags:
      - 'v*' 
    # branches:
    #   - main
    #   - actionTest

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    strategy:
      matrix:
        node-version: 
          - 18.x

    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'

      - name: Install dependencies
        run: npm install

      - name: Build application
        run: npm run build

      - name: Install Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: Run Build to C code
        run: python3 main.py

      - name: Generate Changelog
        run: echo "# Good things have arrived" > ${{ github.workspace }}-CHANGELOG.txt

      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          body_path: ${{ github.workspace }}-CHANGELOG.txt
          name: "Cleaner Website" ${{ github.ref }}
          files: website.h
          token: ${{ secrets.TOKEN }}

      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: my-artifact
          path: website.h
          
  # Add a new job to create a release
  release:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Download artifact
        uses: actions/download-artifact@v2
        with:
          name: my-artifact
          path: website.h

      - name: ls
        run: ls -al

      # - name: Release
      #   uses: softprops/action-gh-release@v1
      #   if: startsWith(github.ref, 'refs/tags/')
      #   with:
      #     name: "Cleaner Website" ${{ github.ref }}
      #     files: website.h
      #     token: ${{ secrets.TOKEN }}