name: Node.js CI

on:
  push:
    tags:
      - 'v*' 
    # branches:
    #   - main
    #   - actionTest

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    strategy:
      matrix:
        node-version: 
          - 18.x

    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'

      - name: Install dependencies
        run: npm install

      - name: Build application
        run: npm run build

      - name: Install Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: Run Build to C code
        run: python3 main.py

  # Add a new job to create a release
  release:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          body: |
            Changes in this Release
            - Add feature A
            - Fix issue B
          draft: false
          prerelease: false

      # Add a new step to upload the website.h file as an asset
      - name: Upload Website Header
        uses: actions/upload-artifact@v2
        with:
          name: website Header
          path: ./website.h
          
      # Add a new step to attach the website.h file to the release
      - name: Attach Website Header to Release
        id: attach_website_header
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./website.h
          asset_name: website.h
          asset_content_type: text/plain